# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.0.0-deps-{{ checksum "frontend/yarn.lock" }}
            - v1.0.0-deps-
      - run:
          name: Package Install
          command: cd frontend && yarn install --frozen-lockfile
      - save_cache:
          key: v1.0.0-deps-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
      - run:
          name: Lint Check
          command: cd frontend && yarn lint
      - run:
          name: Test Frontend
          command: cd frontend && yarn test
      - run:
          name: Frontend Build
          command: cd frontend && yarn build
# Orchestrate or schedule a set of jobs
workflows:
  example-workflow:
    jobs:
      - build
